---
title: "point_data"
author: "Stephen Roecker"
date: "12/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# LDM Sqlite

```{r ldm}

# https://new.cloudvault.usda.gov/index.php/s/eSoPYbWDBQNX2HP

library(DBI)
library(aqp)
library(dplyr)


con <- dbConnect(RSQLite::SQLite(), "C:/Users/stephen.roecker/OneDrive - USDA/data/ldm/LDM-compact_20200709.sqlite")
# area <- read.csv("C:/Users/stephen.roecker/Nextcloud/data/ldm/lab_area.txt", stringsAsFactors = FALSE)
# dbCreateTable(con, "area", area)
(ldm_names <- dbListTables(con))
ldm <- lapply(ldm_names, function(x) dbReadTable(con , x))
names(ldm) <- ldm_names
dbDisconnect(con)



# horizon table
chem_vars <- c("labsampnum", "total_carbon_ncs", "organic_carbon_walkley_black", "estimated_organic_carbon", "cec_nh4_ph_7", "base_sat_nh4oac_ph_7", "caco3_lt_2_mm")
phys_vars <- c("labsampnum", "texture_lab", "clay_total", "silt_total", "sand_total", "total_frag_wt_pct_gt_2_mm_ws", "bulk_density_third_bar", "estimated_organic_matter")
l_vars <- c("labsampnum", "layer_key", "pedon_key", "hzn_desgn", "hzn_top", "hzn_bot")

h <- merge(ldm$layer[l_vars],
           ldm$physical[! duplicated(ldm$physical$labsampnum), phys_vars],
           by = "labsampnum",
           all.x = TRUE
           )
h <- merge(h, 
           ldm$chemical[chem_vars],
           by = "labsampnum",
           all.x = TRUE
           )

h <- within(h, {
  estimated_organic_carbon = ifelse(
    complete.cases(total_carbon_ncs, caco3_lt_2_mm),
    round(total_carbon_ncs - caco3_lt_2_mm / 2.274 * 0.272, 1),
    estimated_organic_carbon
    )
  estimated_organic_carbon = ifelse(
    is.na(estimated_organic_carbon), 
    total_carbon_ncs,
    estimated_organic_carbon
    )
  estimated_organic_carbon = ifelse(
    is.na(estimated_organic_carbon),
    organic_carbon_walkley_black,
    estimated_organic_carbon
    )
  estimated_organic_matter = estimated_organic_carbon * 1.72
})


# site table
ncss_vars <- c("site_key", "pedon_key", "pedlabsampnum", "pedoniid", "samp_name", "corr_name", "samp_classdate", "corr_classdate")
site_vars <- c("site_key", "user_site_id", "latitude_std_decimal_degrees", "longitude_std_decimal_degrees")

s <- merge(ldm$nasis_ncss[ncss_vars],
           ldm$nasis_site[site_vars],
           by = "site_key",
           all.x = TRUE
           )

s_dates <- soilDB::SDA_query("SELECT pedon_key, samp_classdate, corr_classdate FROM lab_combine_nasis_ncss;")

s[c("samp_classdate", "corr_classdate")] <- NULL
s$pedon_key <- as.integer(s$pedon_key)
s <- merge(s, s_dates, by = "pedon_key", all.x = TRUE)

s <- within(s, {
            samp_classdate = strptime(samp_classdate, format = "%m/%d/%Y %H:%M:%S %p")
            corr_classdate = strptime(corr_classdate, format= "%m/%d/%Y %H:%M:%S %p")
            samp_year      = as.integer(format(samp_classdate, "%Y"))
            corr_year      = as.integer(format(corr_classdate, "%Y"))
            year           = ifelse(samp_year < corr_year, samp_year, corr_year)
            })
s <- s[with(s, order(corr_classdate, samp_classdate, decreasing = TRUE)), ]
s$pedon_key <- as.character(s$pedon_key)

h2 <- h
h2 <- h2[h2$pedon %in% s$pedon_key, ]
s <- s[s$pedon_key %in% h2$pedon_key, ]

# build SPC ----
ldm_bs <- h2
ldm_bs$pedon_key <- as.character(ldm_bs$pedon_key)
depths(ldm_bs) <- pedon_key ~ hzn_top + hzn_bot
site(ldm_bs) <- s

# save(ldm, ldm_bs, file = "D:/geodata/project_data/gsp-bs/data/LDM-compact_20200709.RData")

View(test <- subset(horizons(ldm_bs), complete.cases(total_carbon_ncs, estimated_organic_carbon) & !is.na(caco3_lt_2_mm) & caco3_lt_2_mm > 0)[c(3:6, 16:17, 20)])

test$C <- with(test, round(total_carbon_ncs - caco3_lt_2_mm / 2.274 * 0.272, 1))

```


# RaCA

```{r}

raca_xy <- as.data.frame(readxl::read_excel("C:/Users/stephen.roecker/OneDrive - USDA/projects/gsp-bs/data/RaCA_data_summary.xlsx", sheet = "RaCA_xy"))
raca_h <- as.data.frame(readxl::read_excel("C:/Users/stephen.roecker/OneDrive - USDA/projects/gsp-bs/data/RaCA_data_summary.xlsx", sheet = "RaCA_samples_wmodelBD"))

raca_xy <- sf::st_as_sf(
  raca_xy,
  coords = c("Lon", "Lat"),
  crs = "4326"
)
mapview::mapview(raca_xy, maptypes = "OpenStreetMap")


View(subset(horizons(ldm_bs), complete.cases(total_carbon_ncs, estimated_organic_carbon))[c(3:6, 16:17)])
# page 656 KSSL Methods
# page 448 SSSA Methods
# gCO2 = CaCO3 / 2.274 / 100 * 30g
# C = gCO2 * 0.272 / 30g * 100

vars <- c("user_site_id", "upedonid", "rcasiteid", "hzname", "hor_top", "hor_bot", "texture", "fragvolc", "c_tot_ncs", "caco3", "Measure_BD")
rh <- raca_h[vars]
names(rh)[c(1, 4:11)] <- c("usiteid", "hzn_desgn", "hzn_top", "hzn_bot", "texture_lab", "total_frag_wt_pct_gt_2_mm_ws", "total_carbon_ncs", "caco3_lt_2_mm", "bulk_density_third_bar")

rh$total_carbon_ncs <- as.numeric(rh$total_carbon_ncs)
rh$caco3_lt_2_mm    <- as.numeric(rh$caco3_lt_2_mm)
rh$bulk_density_third_bar <- as.numeric(rh$bulk_density_third_bar)
rh <- within(rh, {
  estimated_organic_carbon = round(total_carbon_ncs - caco3_lt_2_mm / 2.274 * 0.272, 1)
  estimated_organic_carbon = ifelse(is.na(estimated_organic_carbon), total_carbon_ncs, estimated_organic_carbon)
  estimated_organic_matter = estimated_organic_carbon * 1.72
})

```


# Field pedons

```{r field-pedons}

source('C:/workspace2/github/ncss-tech/gsp-bs/validate.R')


# load pedons
load(file = "D:/geodata/project_data/gsp-bs/data/LDM-compact_20200709.RData")
lp <- ldm_bs; rm(ldm_bs)

load(file = "nasis_pedons_20201112.RData")
fp <- spc


# filter duplicates ----
s <- site(fp)
s$classdate <- strptime(s$classdate, "%Y-%M-%d")
s <- s[order(s$pedlabsampnum, s$classtype, s$classdate, method = "radix", decreasing = c(FALSE, FALSE, TRUE)), ]
# peiid_nodups <- subset(s, ! duplicated(pedlabsampnum, incomparables = NA))$peiid
peiid_nodups <- subset(s, ! duplicated(paste(pedlabsampnum, usiteid, upedonid, rcasiteid)))$peiid

idx_nodups <- which(
  fp$pedlabsampnum %in% lp$pedlabsampnum 
  & site(fp)$peiid %in% peiid_nodups
  | fp$rcasiteid %in% rh$rcasiteid
  )
fp_bs <- fp[idx_nodups, ]


# merge lab and field pedons
vars <- c("usiteid", "peiid", "upedonid", "pedlabsampnum", "rcasiteid")
s <- site(fp_bs)[vars]
vars <- c("peiid", "hzname", "hzdept", "hzdepb", "d_hue", "d_value", "d_chroma", "m_hue", "m_value", "m_chroma")
h <- horizons(fp_bs)[vars]
h <- left_join(s, h, by = "peiid")


ls <- site(lp)[c("pedon_key", "pedlabsampnum")]
lh <- horizons(lp)
lh$pedon_key <- as.character(lh$pedon_key)
lh <- left_join(ls, lh, by = "pedon_key")


# some don't join, why???
lh2 <- left_join(lh, h, by = c("pedlabsampnum" = "pedlabsampnum", "hzn_top" = "hzdept", "hzn_bot" = "hzdepb"))
lh2 <- lh2[!duplicated(lh2$hzID) & !is.na(lh2$peiid), ]


# merge raca and field pedons
# some don't join, why???
rh$hzID <- as.character(1:nrow(rh))
rh$usiteid <- NULL
rh2 <- left_join(rh, h, by = c("upedonid", "rcasiteid", "hzn_top" = "hzdept", "hzn_bot" = "hzdepb"))
rh2 <- rh2[!duplicated(rh2$hzID) & !is.na(rh2$peiid), ]

names(lh2)[!names(lh2) %in% names(rh2)]

rh2 <- within(rh2, {
  pedon_key    = NA
  labsampnum   = NA
  layer_key    = NA
  clay_total   = NA
  silt_total   = NA
  sand_total   = NA
  cec_nh4_ph_7 = NA
  base_sat_nh4oac_ph_7 = NA
  organic_carbon_walkley_black = NA
})

rh2 <- rh2[names(lh2)]


# combine raca and kssl ----
lh2 <- rbind(lh2, rh2)


# fix and remove O horizons ----
h2 <- validate_depths(lh2, id = "peiid", top = "hzn_top", bot = "hzn_bot")


# bad Os
idx_bad_o <- unique(subset(h2, ! valid_dep_all & grepl("^O", hzn_desgn))$peiid)
# View(h2[h2$pedon_key %in% idx_bad_o, ])

h2_bad_o_fix <- h2 %>%
  filter(peiid %in% idx_bad_o) %>%
  mutate(thk = abs(hzn_bot - hzn_top)) %>%
  group_by(peiid) %>%
  mutate(hzn_top = c(0, cumsum(thk)[-length(thk)]),
         hzn_bot = cumsum(thk)
         ) %>%
  ungroup() %>%
  mutate(thk = NULL)
h2_good_o <- h2[! h2$peiid %in% idx_bad_o, ]

h22 <- rbind(h2_good_o, h2_bad_o_fix)
h22 <- h22[, !grepl("^valid_", names(h22))]


# remove Os
idx_o <- unique(subset(h22, grepl("^O", hzn_desgn))$peiid)

h22_o <- h22 %>%
  filter(peiid %in% idx_o) %>%
  mutate(thk = abs(hzn_bot - hzn_top),
         ) %>%
  group_by(peiid) %>%
  # filter top O horizons
  filter(between(row_number() ,grep("^O", hzn_desgn, invert = TRUE)[1], n())) %>%
  mutate(hzn_top = c(0, cumsum(thk)[-length(thk)]),
         hzn_bot = cumsum(thk)
         ) %>%
  ungroup() %>%
  mutate(thk = NULL)

h22 <- rbind(h22_o, h22[!h22$peiid %in% idx_o, ])


h222 <- validate_depths(h22, id = "peiid", top = "hzn_top", bot = "hzn_bot", order = TRUE, pad_bot = TRUE, rmHzErrors = TRUE)


# extract 0-25cm
h222_seg <- segment(h222, intervals = c(0, 25), hzdepcols = c("hzn_top", "hzn_bot"))

idx_max <- aggregate(hzn_top ~ peiid, data = h222_seg, FUN = function(x) max(x, na.rm = TRUE) <= 25, na.action = na.pass)

h222_seg <- subset(h222_seg, peiid %in% idx_max$peiid[idx_max$hzn_top == TRUE])

bs_spc <- h222_seg
depths(bs_spc) <- peiid ~ hzn_top + hzn_bot
site(bs_spc) <- ~ usiteid
site(bs_spc) <- ~ upedonid
site(bs_spc) <- ~ pedon_key
site(bs_spc) <- ~ pedlabsampnum
site(bs_spc) <- ~ rcasiteid
site(bs_spc) <- site(fp)[c("peiid", "x_std", "y_std", "taxonname", "taxonname_recent", "obsdate", "classdate")]

# save(bs_spc, file = "D:/geodata/project_data/gsp-bs/data/spc_bs.RData")

```


# Impute Color

```{r}

library(rms)

load("D:/geodata/project_data/gsp-bs/data/spc_bs.RData")

# from https://github.com/dylanbeaudette/parse-osd/tree/master/R/models
load("C:/workspace2/github/ncss-tech/gsp-bs/missing-color-models.rda")

h <- horizons(bs_spc)
bs_col <- h[grepl("hzID|^d_|^m_", names(h))]
names(bs_col) <- gsub("d_", "dry_", names(bs_col))
names(bs_col) <- gsub("m_", "moist_", names(bs_col))

bs_col$dry_value_predict    <- round(predict(m.value.dry, bs_col))
bs_col$dry_chroma_predict   <- round(predict(m.chroma.dry, bs_col))
bs_col$moist_value_predict  <- round(predict(m.value.moist, bs_col))
bs_col$moist_chroma_predict <- round(predict(m.chroma.moist, bs_col))

bs_col2 <- transform(
  bs_col,
  # dry
  dry_hue      = ifelse(is.na(dry_hue),      moist_hue,            dry_hue),
  dry_value    = ifelse(is.na(dry_value),    dry_value_predict,    dry_value),
  dry_chroma   = ifelse(is.na(dry_chroma),   dry_chroma_predict,   dry_chroma),
  # moist
  moist_hue    = ifelse(is.na(moist_hue),    dry_hue,              moist_hue),
  moist_value  = ifelse(is.na(moist_value),  moist_value_predict,  moist_value),
  moist_chroma = ifelse(is.na(moist_chroma), moist_chroma_predict, moist_chroma)
  )

summary(bs_col)
summary(bs_col2)

names(bs_col2) <- gsub("^dry_",   "d_", names(bs_col2))
names(bs_col2) <- gsub("^moist_", "m_", names(bs_col2))

bs_col2 <- bs_col2[1:7]

bs_spc2 <- bs_spc
horizons(bs_spc2)[grepl("^d_|^m_", names(horizons(bs_spc2)))] <- NULL
horizons(bs_spc2) <- bs_col2

```


# Classify BS

```{r}

library(sf)

test1 <- allocate(bs_spc, OC = "estimated_organic_carbon", CEC = "cec_nh4_ph_7", BS = "base_sat_nh4oac_ph_7", to = "FAO Black Soil")
test2 <- allocate(bs_spc2, OC = "estimated_organic_carbon", CEC = "cec_nh4_ph_7", BS = "base_sat_nh4oac_ph_7", to = "FAO Black Soil")

summary(test1)
summary(test2)

s <- site(bs_spc2)
s <- merge(s, test2, by = "peiid", all.x = TRUE)

s_sub <- subset(s, complete.cases(x_std, y_std))

s_sf <- st_as_sf(
  s_sub,
  coords = c("x_std", "y_std"),
  crs = 4326
)

s_sf <- within(s_sf, {
            obsdate    = as.Date(obsdate)
            classdate  = as.Date(classdate)
            obs_year   = as.integer(format(obsdate, "%Y"))
            class_year = as.integer(format(classdate, "%Y"))
            year       = ifelse(obs_year < class_year, obs_year, class_year)
            decade     = floor(year * 0.1) * 10
})

table(decade = s_sf$year, black_soil = s_sf$BS2)
View(bs_spc@horizons[grepl("pedon_key|hzname|hzn_top|hzn_bot|estimated_organic_carbon|^d_|^m_", horizonNames(bs_spc))])

# s_sf <- subset(s_sf, !is.na(BS2))

mapview::mapview(s_sf, zcol = "BS1")

# saveRDS(s_sf, file = "D:/geodata/project_data/gsp-bs/data/tdata_bs.rds")

```

